will-hedges/nss-exomine

- scripts/database.js
There are five mineral objects inside the mineral property
> added minerals property to database

- scripts/database.js
Added 5 colonies to `database.js` - each colony has:
- an `id` (primary key)
- a `name` (varchar)
> Added colonies to database

- scripts/database.js
created a governors list in the database.
> governors list

- scripts/database.js
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
Please delete options that are not relevant.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
> Jr initial

- scripts/database.js
facilityInventories has 9 objects
> Lag project

- scripts/database.js
Added colony getter, setter to database file
> added getColonies and setColony to database.js

- scripts/database.js
added getter functions to the database and re organized them
> added getter functions

- index.html
- scripts/Colonies.js
- scripts/Facilities.js
- scripts/FacilityInventories.js
- scripts/Governors.js
- scripts/Minerals.js
- scripts/database.js
- scripts/exomine.js
- scripts/main.js
Modules linked up
IT'S UGLY BUT IT WORKS
> modules rendering

- scripts/Facilities.js
Facilities added to facility module in drop down box.
> Facilities Drop down added to facilities module

- scripts/Facilities.js
Added change event listener to Facilities.js, adds transitory data to transientData object in database
> Added change event listener to Facilities.js

- scripts/Governors.js
updated the initial value for the governors selection
> governors list update

- scripts/database.js
close #31 
fixed the transient state of the setGovenor function to set the correct property in transientState { }
> fixed the gov transient setter

- scripts/SpaceCart.js
- scripts/exomine.js
- placed header, div container, button on page
- closes #28
> placed space cart + purchase button on page

- scripts/FacilityInventories.js
- scripts/database.js
Ticket #32 
I added the getTransientData function in database.js, which is needed for multiple modules.
> getTransientData function

- scripts/database.js
close #24 added more governors some are inactive
> added more govenors, some are inactive

- scripts/Governors.js
close #23 
governors dropdown menu only displays active governors
> gov dropdown only contains active governors

- scripts/Colonies.js
- scripts/Governors.js
* also some random auto-formatting
> choosing a governor now shows the correct colony

- index.html
- scripts/exomine.js
- styles/main.css
Added HTML  to Exomine.js
Added CSS formatting.
> Added CSS and HTML Styling.

- scripts/FacilityInventories.js
- scripts/database.js
Code changed in database.js and FacilityInventories.js to allow proper functionality for the display.
> Facility's inventories displayed when selected in facility dropdown

- scripts/Facilities.js
Added code to Facilities.js that will remove any facility from the dropdown if they've been marked inactive. Ticket #47
> Removed inactive facilities from facility dropdown

- scripts/Colonies.js
- scripts/ColonyInventories.js
- scripts/database.js
- scripts/exomine.js
> Changing the governor now display's that colony's inventory

- scripts/SpaceCart.js
> cart displays 1 ton of selected material

- scripts/SpaceCart.js
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
Please delete options that are not relevant.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
> spacecart output formatting

- scripts/SpaceCart.js
- last PR overwrote header, purchase button
- moved event handler to `id="space-cart"` from `id="space-cart__container"`
> moved 'mat: 1 ton' into space-cart div

- scripts/SpaceCart.js
- shows ex. "1 ton of Iron from Ganymede"
> space cart now shows source colony

- scripts/exomine.js
- styles/main.css
added a 5% border to the left and right of the document and centered the head display.
> added border, centered head

- scripts/ColonyInventories.js
- scripts/FacilityInventories.js
- scripts/Minerals.js
- scripts/SpaceCart.js
- scripts/database.js
- scripts/main.js
Made changes to many files in order to get the purchase button's increment and de-increment.
Also deleted Minerals.js
Ticket #30
> Purchase button functionality

- scripts/SpaceCart.js
Fixed whatever I broke in Space Cart. Should work fine now.
> Fixed Space Cart

- scripts/Colonies.js
- scripts/Governors.js
- styles/main.css
Added a document.query selector and rendered page to clear governors when the default choice was selected. 
Please review and respond accordingly. Thanks
> Jr space cart format

- scripts/FacilityInventories.js
Coded in logic to test inventory amount greater than zero
> Coded in logic to test for inventories to go to zero

- scripts/Facilities.js
close #68 
this made me wanna blow my brains out
> space cart clearing
